spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mariadb://database-study-2.cdnxkpguqzfr.ap-northeast-2.rds.amazonaws.com/study
    driver-class-name: org.mariadb.jdbc.Driver
    username: nxmileadmin
    password: nxmileadmin12#

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
#    deserialization:
#      fail-on-unknown-properties: true